### ISSUE TITLE
clips size

### ISSUE THREAD

**Issue by TMKowiczanin** [jfrey-xx/OpenBCI_3DPrint_misc#1]
Hello
What is the clips size in case_gold_v1 ? I mean diameters.

**Comment by jfrey-xx** [comment]
Hello,

The printed size of the object should be something like 9 x 24.5 x 13mm but I *might* have got the scale wrong in the STL files, e.g. in the slicer Cura I had to scale up by a factor 10 in order to get those measurement. If you are after the diameter of the depression meant to fit the gold cup electrode, it is  around 10 mm.
